name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . -f DockerFile.dev -t rohithmudiraj/docker-react

    - name: Run tests inside Docker container
      run: docker run rohithmudiraj/docker-react npm run test
